### ISSUE TITLE
Make it easier to identify emitted photons.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#57] opened 2024-08-23 16:11 UTC
Running with `?debugEmissions` puts a red circle around photons that are emitted by the atom. This was intended to aid with debugging, to make the emitted photons easier to see.  For example:

<img width="487" alt="screenshot_3481" src="https://github.com/user-attachments/assets/cd0473ed-c511-484b-b34e-ded3023aca59">

I'm finding the `?debugEmissions` feature so useful that I'm wondering if it might be good to do something like this for the production version. Making it easier to identify emitted photons seems like it would improve usability, as well as effectiveness of the sim. @DianaTavares @arouinfar thoughts?

Using `?debugEmissions` also exposed a problem for the Bohr and de Broglie models.  When a photon is emitted, it's direction is randomly chosen.  If this occurs for n = 6 (whose orbit is at the outer edge of the box), the direction chosen may immediately move the photon outside the box, so fast that you don't even see it.   So I think the direction needs to be a function of n.

**Comment by DianaTavares** [comment] 2024-08-26 16:59
I love the idea of a way to identify better the emitted photon, and a red circle is brilliant! 
Good observation that the n=6, the emitted photon goes away of the view fast. I agree with the idea of a direction as a function of n.

@arouinfar is on vacation. If a second opinion is needed, probably @Nancy-Salpepi or @kathy-phet can give their opinion about these ideas.

**Comment by Nancy-Salpepi** [comment] 2024-08-26 17:34
This could be helpful, but I am concerned that students will following the red circle and miss what the electron is doing. @pixelzoom, @DianaTavares and I weren't able to get the query parameter working on main. Is it currently disabled?

**Comment by pixelzoom** [comment] 2024-08-26 18:00
Sorry, my bad... The query paramerter is actually `?debugEmission` (singular).

I think the red circle is a little too heavy-handed, and I was looking for other ideas.  I share @Nancy-Salpepi's concern.  And I have an additional concern -- that students may think emitted photons are somehow different because they look different.    But I think something a little more subtle might be useful, because sometimes it's difficult to even notice that a photon was emitted.

**Comment by Nancy-Salpepi** [comment] 2024-08-26 18:31
I'm going to back to trying to find some real estate for the 'slow' radio button because that would definitely make it easier to see what is happening.

**Comment by DianaTavares** [comment] 2024-08-26 19:13
I see now how the red stroke takes the attention of the electron, and  yes, also leads to think that the photons emitted are different from the absorbed. I have some crazy ideas:

- ![image](https://github.com/user-attachments/assets/33b4602e-b52c-4f8a-9d50-062d5a4f8cbc)

 add the step back button, to allow students to go back and see more clear what happened.  Because can pass very fast, both, the abortion and emission, and the change of n.

- Sounds, one when the photon is absorbed, and the other when it is emitted. (I'm imaging similar to grab and release, something long of those lines).  

- Also identify that a photon was observed, can also be lost. What about a little shinning for the electron (that just have like a second duration, probably just when the electron absolve/emitted the photon, and move to the new level) as in molecules and light:

![image](https://github.com/user-attachments/assets/e1a91bff-3dad-4276-9696-d7f673645b59)
Well this don't solve the problem that the photon is the one that may get lost, because it just make bigger the change in the electron, and that is very evident in all cases. 


- The yellow shining goes around the photon and electron when it is emitted/absorbed and slow the reproduction a little? in that moment for example:
![image](https://github.com/user-attachments/assets/e50953f2-7042-4a3c-9e99-8b9f04108925)
 
Because it is not important to follow the direction of the Photon, just to know what was absorbed and what was emitted.

Just ideas, thinking more about this.

**Comment by DianaTavares** [comment] 2024-08-30 18:18
During a discussion with AR and NS we discussed that probably the only that we need is the slow button to better observe the emission by the electron. For that the panel need the toggle button need to be smaller to fit the slow option in the play panel 
![image](https://github.com/user-attachments/assets/2df0d9b2-399b-4ca0-afdc-8a33d2a98a39)

**Comment by pixelzoom** [comment] 2024-09-23 14:54
9/19/24 design meeting with @DianaTavares @arouinfar @kathy-phet @pixelzoom.

We will not add a halo to emitted photons, that's too heavy-handed. (`?debugEmission` is still useful to me for debugging, so I'll keep it around.)

We discussed adding a trail to emitted photons, but decided that's also too heavy-handed.

Emitted photons are difficult to see in 2 cases: (1) The photon is emitted in the same direction as the light photons. (2) The photon is emitted from a higher orbit, and its direction causes it to leave the screen quickly.   I will adjust the direction algorithm to prevent these cases.

**Comment by pixelzoom** [comment] 2024-09-30 19:17
> Emitted photons are difficult to see in 2 cases: (1) The photon is emitted in the same direction as the light photons. (2) The photon is emitted from a higher orbit, and its direction causes it to leave the screen quickly. I will adjust the direction algorithm to prevent these cases.

Places where this needs to be addressed:

* BohrModel `attemptSpontaneousEmission`, `direction: MOTHAUtils.nextAngle()`
* PlumPuddingModel `emitPhoton`, `direction: MOTHAUtils.nextAngle()`
* SchrodingerModel `getSpontaneousEmissionPosition`, `angle = MOTHAUtils.nextAngle()`

**Comment by pixelzoom** [comment] 2024-10-06 20:05
Re adjusting the direction of emitted photons so that they are not the same as photons emitted by the light... We have a problem with that decision.  When stimulated emission occurs, the emitted photon is supposed to travel in the same direction as the photon that did the stimulating.

**Comment by pixelzoom** [comment] 2024-10-08 21:14
As we decided in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/57#issuecomment-2368531956, I have optimized the direction of photons that are spontaneously emitted, so that they travel in a direction that is significantly different than the light (currently must differ by PI/8).  When the electron's state n > 4, there is an additional condition that prevents the photon from leaving the view too quickly - the photon takes a path through the atom, towards the nucleus, but not intersecting the nucleus.  I don't know if this is sufficient to address the problem, but it's ready for @DianaTavares to review.

We also still have a problem with stimulated emission.  Over in #70, I was unsure whether stimulated emission was actually occurring, because it's so difficult to see.  I did confirm by enhancing the logging output and using a different color (green) with `?debugEmission`.   But the problem remains for users.  Stimulated emission occurs infrequently, and it's almost impossible to notice it.  Given the amount of work involved in implementing stimulated emissions, that's very sad.  @DianaTavares Thoughts on how to address this? Or do we need to address it?

**Comment by DianaTavares** [comment] 2024-10-08 23:55
I like it!! Even with normal velocity and without debugEmission(because I know what to observe), I can appreciate the emission with white light. When I play with a specific wavelength most of the time it was spontaneous emission, going throw different energy levels before to arrive to n=1, then we see different photons colors going in different directions. Only in a few cases I observe stimulated emission, and I think there is nothing to address. I will add some information about stimulated emission in the teacher tips. 

Closing this issue. Amazing work CM!!

**Closed by DianaTavares** 2024-10-08 23:55 UTC
Labels: design:general, status:ready-for-review
